services:
  msl_mongo:
    image: mongo:latest
    container_name: msl_mongo
    networks:
      msl_network:
        aliases:
          - mongo
    volumes:
      - msl_mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=mongo_pass
    restart: always

  msl_backend:
    image: oliverschlueter/msl-backend:latest
    container_name: msl_backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      # Credentials
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_PASSWORD=mongo_pass
    networks:
      msl_network:
    restart: always

  msl_ai-worker:
    image: oliverschlueter/msl-ai-worker:latest
    container_name: msl_ai-worker
    depends_on:
      - msl_backend
    networks:
      msl_network:
    restart: always

networks:
  msl_network:
    driver: bridge

volumes:
  msl_mongo_data: