services:
  # Our services
  msl_reverseproxy:
    image: oliverschlueter/msl-reverseproxy:latest
    container_name: msl_reverseproxy
    environment:
      - "LOKI_URL=${LOKI_URL}"
      - "CONFIG_PATH=${REVERSE_PROXY_CONFIG_PATH}"
      - "FEATURE_FLAGS_SEND_LOGS_TO_LOKI=${FEATURE_FLAGS_SEND_LOGS_TO_LOKI}"
    networks:
      msl_network:
    ports:
      - "9080:8080"
    volumes:
      - ./reverseproxy:/app/data

  msl_frontend:
    image: oliverschlueter/msl-frontend:latest
    environment:
      - "LOKI_URL=${LOKI_URL}"
      - "FEATURE_FLAGS_SEND_LOGS_TO_LOKI=${FEATURE_FLAGS_SEND_LOGS_TO_LOKI}"
    networks:
      msl_network:
    deploy:
      replicas: 3

  msl_backend:
    image: oliverschlueter/msl-backend:latest
    depends_on:
      - msl_nats
      - msl_mongo
    environment:
      - "LOKI_URL=${LOKI_URL}"
      - "NATS_URL=${NATS_URL}"
      - "MONGODB_URL=mongodb://${MONGODB_USERNAME}:<MONGODB_PASSWORD>@${MONGODB_HOST}:${MONGODB_PORT}"
      - "FEATURE_FLAGS_SEND_LOGS_TO_LOKI=${FEATURE_FLAGS_SEND_LOGS_TO_LOKI}"
    networks:
      msl_network:
    deploy:
      replicas: 3

  msl_aiworker:
    image: oliverschlueter/msl-aiworker:latest
    depends_on:
      - msl_nats
      - msl_mongo
      - msl_qdrant
    environment:
      - "LOKI_URL=${LOKI_URL}"
      - "NATS_URL=${NATS_URL}"
      - "OLLAMA_URL=${OLLAMA_URL}"
      - "QDRANT_HOST=${QDRANT_HOST}"
      - "QDRANT_PORT=${QDRANT_PORT}"
      - "QDRANT_API_KEY=${QDRANT_API_KEY}"
      - "FEATURE_FLAGS_SEND_LOGS_TO_LOKI=${FEATURE_FLAGS_SEND_LOGS_TO_LOKI}"
    networks:
      msl_network:
    deploy:
      replicas: 3

  # Databases
  msl_mongo:
    image: mongo:latest
    container_name: msl_mongo
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}"
    networks:
      msl_network:
        aliases:
          - msl_mongo
    ports:
      - "27017:27017"

  msl_qdrant:
    image: qdrant/qdrant:latest
    container_name: msl_qdrant
    environment:
      - "QDRANT__SERVICE__API_KEY=${QDRANT_API_KEY}"
    networks:
      msl_network:
        aliases:
          - msl_qdrant
    ports:
      - "6333:6333"

  # Other
  msl_nats:
    image: nats:latest
    container_name: msl_nats
    networks:
      msl_network:
        aliases:
          - msl_nats

networks:
  msl_network:
    driver: bridge