openapi: 3.1.1
info:
  title: Mauerstrassenloewen Simulation API
  description: API for interacting with the Mauerstrassenloewen simulation service.
  version: 0.0.1
servers:
  - url: http://localhost:8081
    description: Local server
paths:
  /api/v1/simulation:
    post:
      summary: Create simulation
      description: Create a new simulation.
      tags:
        - Simulation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrUpdateSimulationRequest'
      responses:
        '201':
          description: Simulation created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Simulation'
        '400':
          description: Bad request (invalid request body)
        '404':
          description: Simulation not found
        '500':
          description: Internal server error

  /api/v1/simulation/{simulationId}:
    get:
      summary: Get simulation
      description: Get a simulation by its ID.
      tags:
        - Simulation
      responses:
        '200':
          description: Found simulation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Simulation'
        '400':
          description: Bad request
        '409':
          description: Simulation already exists
        '415':
          description: Unsupported media type
        '500':
          description: Internal server error
    put:
      summary: Update simulation
      description: Update an existing simulation.
      tags:
          - Simulation
      requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Simulation'
      responses:
          '204':
            description: Simulation updated successfully
          '400':
            description: Bad request
          '404':
            description: Simulation not found
          '500':
            description: Internal server error
    delete:
      summary: Delete simulation
      description: Delete a simulation by its ID.
      tags:
        - Simulation
      responses:
        '204':
          description: Simulation updated successfully
        '400':
          description: Bad request
        '404':
          description: Simulation not found
        '500':
          description: Internal server error
components:
  schemas:
    CreateOrUpdateSimulationRequest:
      type: object
      properties:
        name:
          type: string
          example: 'My Simulation'
      required:
        - name
    Simulation:
      type: object
      properties:
        id:
          type: string
          example: '52434ef7-cdb5-4267-9e8b-86eba4e03780'
        name:
          type: string
          example: 'My Simulation'
      required:
        - id
        - name
