openapi: 3.1.1
info:
  title: Mauerstrassenloewen Simulation API
  description: API for interacting with the Mauerstrassenloewen simulation service.
  version: 0.0.1
servers:
  - url: http://localhost:8081
    description: Local server
paths:

components:
  schemas:

