services:
  msl_frontend:
    image: oliverschlueter/msl-frontend:latest
    container_name: msl_frontend
    networks:
      msl_network:
        aliases:
          - msl_frontend
    ports:
        - "9081:8081"

networks:
  msl_network:
    driver: bridge