name: Test backend

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.2

      - name: Create fake frontend files
        run: |
          mkdir -p frontend/dist
          echo "<h1>Hello World!</h1>" > frontend/dist/index.html

      - name: Copy frontend files
        run: |
          cd scripts
          chmod +x copy-frontend-files.sh
          ./copy-frontend-files.sh

      - name: Build project
        run: cd services/backend && go build cmd/e2e/main.go

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.2

      - name: Create fake frontend files
        run: |
          mkdir frontend/dist
          echo "<h1>Hello World!</h1>" > frontend/dist/index.html

      - name: Copy frontend files
        run: |
          cd scripts
          chmod +x copy-frontend-files.sh
          ./copy-frontend-files.sh

      - name: Install dependencies
        run: cd services/backend && go mod tidy

      - name: Run tests
        run: cd services/backend && go test ./... -v