name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24.2'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend/

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend/

      - name: Build docs
        run: |
          npm install retypeapp --global
          retype build
        working-directory: ./docs/

      - name: Copy frontend files
        run: |
          chmod +x copy-frontend-files.sh
          ./copy-frontend-files.sh
        working-directory: ./scripts/

      - name: Build Docker image
        run: docker build -t oliverschlueter/msl-frontend:latest -f DockerfileFrontend .
        working-directory: ./services/

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push oliverschlueter/msl-frontend:latest

  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
          check-latest: true
          cache-dependency-path: "**/*.sum"

      - name: Build Docker image
        run: docker build -t oliverschlueter/msl-backend:latest -f DockerfileBackend .
        working-directory: ./services/

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push oliverschlueter/msl-backend:latest

  deploy-reverse-proxy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
          check-latest: true
          cache-dependency-path: "**/*.sum"

      - name: Build Docker image
        run: docker build -t oliverschlueter/msl-reverseproxy:latest -f DockerfileReverseproxy .
        working-directory: ./services/

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push oliverschlueter/msl-reverseproxy:latest

  deploy-ai-worker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
          check-latest: true
          cache-dependency-path: "**/*.sum"

      - name: Build Docker image
        run: docker build -t oliverschlueter/msl-aiworker:latest -f DockerfileAIWorker .
        working-directory: ./services/

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push oliverschlueter/msl-aiworker:latest

  deploy-monitoring:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
          check-latest: true
          cache-dependency-path: "**/*.sum"

      - name: Build Docker image
        run: docker build -t oliverschlueter/msl-monitoring:latest -f DockerfileMonitoring .
        working-directory: ./services/

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push oliverschlueter/msl-monitoring:latest