name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24.2'

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.2.0'

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend/

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend/

      - name: Copy frontend files
        run: |
          chmod +x copy-frontend-files.sh
          ./copy-frontend-files.sh
        working-directory: ./scripts/

      - name: Build Docker image
        run: |
          docker build -t oliverschlueter/msl-frontend:latest -f DockerfileFrontend .
        working-directory: ./services/

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push oliverschlueter/msl-frontend:latest

