name: Test simulation

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
          check-latest: true
          cache-dependency-path: "**/*.sum"

      - name: Build project
        run: cd services/simulation && go build cmd/e2e/main.go

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
          check-latest: true
          cache-dependency-path: "**/*.sum"

      - name: Install dependencies
        run: cd services/simulation && go mod tidy

      - name: Run tests
        run: cd services/simulation && go test ./... -v